#!/usr/bin/with-contenv sh

export HDX_CPSDB_ADDR=dbcps
export HDX_CPSDB_PORT=5432
#hdxcpstool pgpass
#python /srv/helper_cps.py

envsubst < $HDX_FOLDER/config/log4j.xml.tpl > $HDX_FOLDER/config/log4j.xml
envsubst < $HDX_FOLDER/config/hdx-config.tpl > $HDX_FOLDER/config/hdx-config

exec . $CATALINA_HOME/bin/catalina.sh start
