#! /bin/sh

set -e

PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
export PATH

# guess path for command_directory
command_directory=`postconf -h command_directory`
daemon_directory=`$command_directory/postconf -h daemon_directory`

# kill Postfix if running
$daemon_directory/master -t || $command_directory/postfix stop

# update the damn files by hand
cp -a /etc/resolv.conf /var/spool/postfix/etc/resolv.conf
cp -a /etc/hosts /var/spool/postfix/etc/hosts

# make consistency check
$command_directory/postfix check >/dev/console 2>&1

# run Postfix
exec $daemon_directory/master
exit $?
