#!/bin/bash

# update hosts
if [ $(grep -c "10.66.32.110" /etc/hosts) -eq 0 ]; then
        echo "10.66.32.110 dev.hdx.rwlabs.org  dev-docs.hdx.rwlabs.org  dev-data.hdx.rwlabs.org  dev-manage.hdx.rwlabs.org"  >> /etc/hosts
fi
if [ $(grep -c "10.66.32.109" /etc/hosts) -eq 0 ]; then
        echo "10.66.32.109 test.hdx.rwlabs.org test-docs.hdx.rwlabs.org test-data.hdx.rwlabs.org test-manage.hdx.rwlabs.org" >> /etc/hosts
fi
if [ $(grep -c "10.66.32.108" /etc/hosts) -eq 0 ]; then
        echo "10.66.32.108 hdx.rwlabs.org      docs.hdx.rwlabs.org      data.hdx.rwlabs.org      manage.hdx.rwlabs.org"      >> /etc/hosts
fi

# configure prod.ini
envsubst < /srv/prod.ini.tpl > /srv/prod.ini

# fix permissions on filestore
mkdir -p /srv/filestore /srv/backup /var/log/ckan
chown www-data:www-data -R /srv/filestore/
chown www-data:www-data -R /var/log/ckan
chown root:root -R /srv/backup

# set pgpass if it's not there
hdxckantool pgpass > /dev/null
# set proper permissions on datastore
hdxckantool db set-perms > /dev/null

#echo "HDX-Ckan starting in 2 seconds..."
#sleep 2
cd /srv
exec gunicorn --paste /srv/prod.ini -c /srv/gunicorn_conf.py
