#!/bin/bash

CKAN_INI="/srv/prod.ini"

# update hosts
if [ $(grep -c "10.66.32.110" /etc/hosts) -eq 0 ]; then
        echo "10.66.32.110 dev.hdx.rwlabs.org  dev-docs.hdx.rwlabs.org  dev-data.hdx.rwlabs.org  dev-manage.hdx.rwlabs.org"  >> /etc/hosts
fi
if [ $(grep -c "10.66.32.109" /etc/hosts) -eq 0 ]; then
        echo "10.66.32.109 test.hdx.rwlabs.org test-docs.hdx.rwlabs.org test-data.hdx.rwlabs.org test-manage.hdx.rwlabs.org" >> /etc/hosts
fi
if [ $(grep -c "10.66.32.108" /etc/hosts) -eq 0 ]; then
        echo "10.66.32.108 hdx.rwlabs.org      docs.hdx.rwlabs.org      data.hdx.rwlabs.org      manage.hdx.rwlabs.org"      >> /etc/hosts
fi

# update solr config in ckan ini file
solr_port=$(echo $SOLR_PORT | awk -F \: '{ print $3 }')
#sed -e 's/^tcp:\/\///')
sed -i 's/solr_url.*/solr_url = http:\/\/solr:'$solr_port'\/solr\/ckan/' /srv/prod.ini

# update postgres config
#db_addr=$(echo $DB_PORT | sed -e 's/^tcp:\/\///')
db_port=$(echo $DB_PORT | awk -F \: '{ print $3 }')
db_name=$(echo $DB_ENV_POSTGRESQL_DB)
db_user=$(echo $DB_ENV_POSTGRESQL_USER)
db_pass=$(echo $DB_ENV_POSTGRESQL_PASS)
sed -i 's/^sqlalchemy\.url.*/sqlalchemy\.url = postgresql:\/\/'$db_user':'$db_pass'@db:'$db_port'\/'$db_name'/' /srv/prod.ini

datastore_name=$(echo $DB_ENV_POSTGRESQL_DATASTORE_DB)
datastore_user=$(echo $DB_ENV_POSTGRESQL_DATASTORE_USER)
datastore_pass=$(echo $DB_ENV_POSTGRESQL_DATASTORE_PASS)
sed -i 's/^ckan\.datastore\.write_url.*/ckan\.datastore\.write_url = postgresql:\/\/'$db_user':'$db_pass'@db:'$db_port'\/'$datastore_name'/' /srv/prod.ini
sed -i 's/^ckan\.datastore\.read_url.*/ckan\.datastore\.read_url = postgresql:\/\/'$datastore_user':'$datastore_pass'@db:'$db_port'\/'$datastore_name'/' /srv/prod.ini

# fix filestore path
sed -i 's/^ofs\.storage_dir.*/ofs\.storage_dir = \/srv\/filestore/' /srv/prod.ini
sed -i 's/^ckan\.storage_path.*/ckan\.storage_path = \/srv\/filestore/' /srv/prod.ini

# set pgpass if it's not there
hdxckantool pgpass
#pass_line="db:"$db_port":*:"$db_user":"$db_pass
#pgpass_file="/root/.pgpass"
#if [ ! -f $pgpass_file ] || [ "$pass_line" != "$(head -n 1 $pgpass_file)" ]; then
#    echo $pass_line > $pgpass_file
#    chmod 600 $pgpass_file
#fi
# make sure datastore privs are set
#psql -h db -U $db_user $datastore_name -f /srv/set-perms.sql
hdxckantool set-perms

echo "HDX-Ckan starting in 2 seconds..."
sleep 2
cd /srv
exec gunicorn --paste /srv/prod.ini -c /srv/gunicorn_conf.py
