#!/bin/bash

# configure prod.ini
envsubst < /srv/prod.ini.tpl > /srv/prod.ini
#configure test ini
envsubst < /srv/hdx-test-core.ini.tpl > /srv/ckan/hdx-test-core.ini

# fix permissions on filestore
mkdir -p /srv/filestore /srv/backup /var/log/ckan
#chown www-data:www-data -R /srv/filestore/
#chown www-data:www-data -R /var/log/ckan
#chown root:root -R /srv/backup

python /srv/helper.py

# set pgpass if it's not there
hdxckantool pgpass > /dev/null
# set proper permissions on datastore
hdxckantool db set-perms > /dev/null

# make ckan dependent on pgb
sv start pgb || exit 1

#hdxckantool less compile

#echo "HDX-Ckan starting in 2 seconds..."
#sleep 2
cd /srv/ckan

[ -z $NEW_RELIC_CONFIG  ] && export NEW_RELIC_CONFIG=/srv/newrelic.ini
[ -z $NEW_RELIC_ENABLED ] && export NEW_RELIC_ENABLED=false
[ -z $NEW_RELIC_LICENSE ] && export NEW_RELIC_LICENSE="LICENSE"

if [ "$NEW_RELIC_ENABLED" == "true" ]; then
    echo "new relic is enabled."
    newrelic-admin generate-config $NEW_RELIC_LICENSE $NEW_RELIC_CONFIG
    exec newrelic-admin run-program gunicorn --paste /srv/prod.ini -c /srv/gunicorn_conf.py
else
    echo "new relic is disabled."
    exec gunicorn --paste /srv/prod.ini -c /srv/gunicorn_conf.py
fi
