#!/bin/bash
set -e

dbhost=${HDX_GISDB_ADDR}
dbport=${HDX_GISDB_PORT}

# make sure postgis extension are enabled on psql
[ "$(psql -h $dbhost -p $dbport gis gis -c '\dx' | grep -c  postgis\ )" -eq "1" ] || psql -h $dbhost -p $dbport gis gis -c 'CREATE EXTENSION postgis;'
# make sure postgis_topology extension are enabled on psql
[ "$(psql -h $dbhost -p $dbport gis gis -c '\dx' | grep -c  postgis_topology)" -eq "1" ] || psql -h $dbhost -p $dbport gis gis -c 'CREATE EXTENSION postgis_topology;'

# make sure pgpass is up to date
[ "cat /root/.pgpass" -eq "$dbhost:$dbport:*:gis:gis" ] || envsubst < /root/.pgpass.tpl > /root/.pgpass

# regenerate app.conf
envsubst < /srv/app.conf.tpl > /srv/app.conf

cd /srv/gislayer
export GIS_REST_LAYER_CONF=/srv/app.conf

exec python gis_rest_layer.py
