#!/bin/bash
set -e

# need to know how to purge old, stucked workers!


# make sure pgpass is up to date
dbhost=${HDX_GISDB_ADDR}
dbport=${HDX_GISDB_PORT}
pf="/root/.pgpass"
line="$dbhost:$dbport:*:gis:gis"
[ -f $pf ] || touch $pf
if [ $(cat $pf | grep -cE $line) -ne 1 ]; then
    echo $line > $pf
    chmod 600 $pf
fi

# exit if I can't get my own worker name
#[ "$(env | grep -cE 'DB_NAME.*worker')" -eq "1" ] || exit 1
# set my worker name
#myname=$(env | grep DB_NAME | sed -e 's/.*_gis/gis/; s/\/.*//')
#name="--name "$myname
name=""

#ttl="--worker-ttl 600"
ttl=""

# not needed, it seems
envsubst < /srv/app.conf.tpl > /srv/app.conf
export GIS_REST_LAYER_CONF=/srv/app.conf

cd /srv/gislayer
exec rqworker --url redis://${HDX_GISREDIS_ADDR}:${HDX_GISREDIS_PORT}/1 $name --worker-ttl 600 geo_q
